# generated by datamodel-codegen:
#   filename:  pydantic_gerrit.latest.changes.json
#   timestamp: 2025-09-12T22:47:58+00:00

from __future__ import annotations

from typing import TypedDict

from typing_extensions import NotRequired


class DiffWebLinkInfo(TypedDict):
    name: str
    tooltip: NotRequired[str | None]
    url: str
    image_url: NotRequired[str | None]
    show_on_side_by_side_diff_view: bool
    show_on_unified_diff_view: bool
